### ISSUE TITLE
why use this when i can use the discord.js embed builder

### ISSUE THREAD

**Issue by devsnek** [FireController1847/embed-creator#1]

**Comment by FireController1847** [comment]
While they're both good methods, I kind of made this for myself that way I don't need a new line for each item, as well as not having to do an object for each. Both of them are good creators, though, I just prefer this one.

**Comment by eslachance** [comment]
did you know
```js
msg.channel.send({embed: new Discord.RichEmbed().setAuthor("blah").setDescription("blah"));
```
It **can** work on a single line. And you're basically just turning a series of arguments into a series of properties in an object, this thing's essentially completely useless. Sure you can use it for yourself but why bother publishing it on npm, no one is going to use this except nubs that don't know better. So... slowclap there fella.

**Comment by FireController1847** [comment]
@eslachance And this can work in a single line as well.
```javascript
msg.channel.send(ce("#FFFFFF", "blah", null, "blah"));
```
